steps:
  # Step 1: Docker build step
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA'
      - '-f'
      - '${_DOCKERFILE_RELATIVE_PATH}'
      - '.'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA'

  # Step 3: Deploy to Cloud Run and inject secrets as env into runtime
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--network=projects/${PROJECT_ID}/global/networks/${_VPC_NETWORK_NAME}'
      - '--subnet=projects/${PROJECT_ID}/regions/${_REGION}/subnetworks/${_SUBNET_NAME}'
      - '--vpc-egress=private-ranges-only'
      - '--ingress=all'
      - '--labels=${_LABELS}'


# Timeout for the build process
timeout: 1500s

substitutions:
  _IMAGE_NAME: '[Enter here Image Name]'
  _REPOSITORY_NAME: '[Enter here Repository Name]'
  _DOCKERFILE_RELATIVE_PATH: './deployment/Dockerfile'
  _SERVICE_NAME: '[Enter here service name]'
  _LABELS: 'env=production'
  _REGION: 'us-central1'
  _VPC_NETWORK_NAME: '[Enter here vpc network name]'
  _SUBNET_NAME: '[Enter here subnet name]'


options:
  logging: CLOUD_LOGGING_ONLY
